Fix `UnicodeDecodeError`
Previously, when using the Latin alphabet, an error occurred:
`self.selection = [str(get_path(pidl).decode('utf-8'))]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 24: invalid continuation byte`.
So that this error no longer occurs, the encoding was changed to `Windows-1251`, and such errors now do not lead to the termination of the program with an error.